<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Page Not Found</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/animate.css" rel="stylesheet">
	<link href="/css/style.css" rel="stylesheet">

	<link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
</head>

<body>

<div class="navbar navbar-static-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">App Store</a>
		</div>
	</div>
</div>

<div class="container">

	<div class="row">
		<div class="span12">
			<div class="hero-unit animated fadeIn">
				<h1>404</h1>
				<p>This page was not found, it could have been deleted or is no longer active.</p>

				<div class="row">
					<div class="span12">
						<a href="/" class="btn btn-large">&laquo; To Homepage</a>
					</div>
				</div>
			</div>
		</div>
	</div>

</div> <!-- /container -->

</body>
</html>